In [41]:
def clean(floor): 
    i, j, row, col = 0, 0, len(floor), len(floor[0])
    for i in range(row):
        if(i%2 == 0):
            for j in range(col):
                if(floor[i][j] == 1):
                    print_F(floor, i, j)
                    floor[i][j] = 0
                print_F(floor, i, j)
        else:
            for j in range(col-1, -1, -1):
                if(floor[i][j] == 1):
                    print_F(floor, i, j)
                    floor[i][j] = 0
                print_F(floor, i, j)

def print_F(floor, row, col):
    print("The Floor matrix is as below:")
    for r in range(len(floor)):
        for c in range(len(floor[r])):
            if r == row and c == col:
                print(f" >{floor[r][c]}< ", end = '')
            else:
                print(f"  {floor[r][c]}  ", end = '')
        print(end = '\n')
    print(end = '\n')


def main():
    floor = []
    m = int(input("Enter the No. of Rows: "))
    n = int(input("Enter the No. of Columns: "))
    print("Enter clean status for each cell (1 - dirty, 0 - clean)")
    for i in range(m):
        f = list(map(int, input().split(" ")))
        floor.append(f)
    print()
    clean(floor)

In [115]:
def express(floor,m,n):
    for i in range(m):
        col = range(n) if i%2 == 0 else range(n-1,-1,-1)
        for j in col:
            if floor[i][j] == 1:
                floor[i][j] = 0
        print()


def visual(floor,row,col):
    print("The Floor matrix is as below:")
    for r in range(len(floor)):
        for c in range(len(floor[r])):
            if r == row and c == col:
                print(f" >{floor[r][c]}< ", end = '')
            else:
                print(f"  {floor[r][c]}  ", end = '')
        print(end = '\n')
    print(end = '\n')
    
def main():
    floor = []
    m = int(input("Enter row size: "))
    n = int(input("Enter columns size: "))
    print("Enter clean status for each cell (1 - dirty, 0 - clean)")
    for i in range(m):
        row = []
        for j in range(n):
            val = int(input(f"Enter value of {i,j}"))
            row.append(val)
        floor.append(row)

    print("Before Cleaning")
    
    for i in range(m):
        for j in range(n):
            print(f"{floor[i][j]}",end=" ")

        print()

    print("Press 1 for faster cleaning")
    
    print("Press 2 for visual cleaning")

    test = int(input("Enter a number"))

    if(test==1):
        express(floor,m,n)
    else:
        visual(floor,m,n)
    
    print("After Cleaning")

    for i in range(m):
        for j in range(n):
            print(f"{floor[i][j]}",end=" ")

        print()
                

In [117]:
main()

Enter row size:  3
Enter columns size:  3


Enter clean status for each cell (1 - dirty, 0 - clean)


Enter value of (0, 0) 1
Enter value of (0, 1) 0
Enter value of (0, 2) 1
Enter value of (1, 0) 3
Enter value of (1, 1) 2
Enter value of (1, 2) 1
Enter value of (2, 0) 1
Enter value of (2, 1) 0
Enter value of (2, 2) 0


Before Cleaning
1 0 1 
3 2 1 
1 0 0 
Press 1 for faster cleaning
Press 2 for visual cleaning


Enter a number 2


The Floor matrix is as below:
  1    0    1  
  3    2    1  
  1    0    0  

After Cleaning
1 0 1 
3 2 1 
1 0 0 


In [135]:
def main():
    floor = []
    m = int(input("Enter row size: "))
    n = int(input("Enter columns size: "))
    print("Enter clean status for each cell (1 - dirty, 0 - clean)")
    for i in range(m):
        row = []
        for j in range(n):
            val = int(input(f"Enter value of {i,j}"))
            row.append(val)
        floor.append(row)

    print("Before Cleaning")
    
    for i in range(m):
        for j in range(n):
            print(f"{floor[i][j]}",end=" ")

        print()

    floor = json.loads(json.dumps(floor).replace("1","0"))  

    print("After Cleaning")

    for i in range(m):
        for j in range(n):
            print(f"{floor[i][j]}",end=" ")

        print()

In [137]:
main()

Enter row size:  3
Enter columns size:  3


Enter clean status for each cell (1 - dirty, 0 - clean)


Enter value of (0, 0) 1
Enter value of (0, 1) 1
Enter value of (0, 2) 1
Enter value of (1, 0) 1
Enter value of (1, 1) 1
Enter value of (1, 2) 1
Enter value of (2, 0) 1
Enter value of (2, 1) 1
Enter value of (2, 2) 1


Before Cleaning
1 1 1 
1 1 1 
1 1 1 
After Cleaning
0 0 0 
0 0 0 
0 0 0 


In [131]:
import numpy as np

def main():
    m = int(input("Enter row size: "))
    n = int(input("Enter column size: "))
    print("Enter clean status for each cell (1 - dirty, 0 - clean)")

    data = []
    for i in range(m):
        row = list(map(int, input(f"Enter row {i} (space-separated): ").split()))
        data.append(row)

    floor = np.array(data)

    print("\nBefore Cleaning:")
    print(floor)

    floor[floor == 1] = 0

    print("\nAfter Cleaning:")
    print(floor)


In [133]:
main()

Enter row size:  3
Enter column size:  3


Enter clean status for each cell (1 - dirty, 0 - clean)


Enter row 0 (space-separated):  0 1 1
Enter row 1 (space-separated):  1 0 0
Enter row 2 (space-separated):  1 1 1



Before Cleaning:
[[0 1 1]
 [1 0 0]
 [1 1 1]]

After Cleaning:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
